name: riverpod_code
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.6.1
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.6.1
  # https://pub.dev/packages/go_router
  go_router: ^14.6.0
  # https://pub.dev/packages/retrofit
  retrofit: ^4.4.1
  # https://pub.dev/packages/dio
  dio: ^5.7.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.1
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/intl
  intl: ^0.20.0
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
